<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_cron().
 */
function filelink_usage_cron() {
  \Drupal::service('filelink_usage.cron')->run();
}

/**
 * Mark a node as needing a rescan.
 */
function filelink_usage_mark_for_rescan(NodeInterface $node) {
  \Drupal::service('filelink_usage.manager')->markForRescan($node);
}

/**
 * Implements hook_entity_insert().
 */
function filelink_usage_entity_insert(EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('filelink_usage.scanner')->scanNode($entity);
  }
}

/**
 * Implements hook_entity_update().
 */
function filelink_usage_entity_update(EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('filelink_usage.scanner')->scanNode($entity);
  }
}

/**
 * Implements hook_entity_delete().
 */
function filelink_usage_entity_delete(EntityInterface $entity) {
  if ($entity instanceof NodeInterface) {
    \Drupal::service('filelink_usage.manager')->cleanupNode($entity);
  }
}
