filelink_usage.settings:
  type: config_object
  label: 'File Link Usage settings'
  mapping:
    verbose_logging:
      type: boolean
      label: 'Verbose logging'
    scan_frequency:
      type: string
      label: 'Cron scan frequency'
      allowed_values:
        - every
        - hourly
        - daily
        - weekly
        - monthly
        - yearly
    scan_batch_size:
      type: integer
      label: 'Scan batch size'
    last_scan:
      type: integer
      label: 'Timestamp of last cron scan'
