filelink_usage.settings:
  type: config_object
  label: 'File Link Usage settings'
  mapping:
    verbose_logging:
      type: boolean
      label: 'Verbose logging'
    scan_frequency:
      type: string
      label: 'Cron scan frequency'
    last_scan:
      type: integer
      label: 'Timestamp of last cron scan'
